# Generated by Django 5.2.4 on 2025-07-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_post_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
