# Generated by Django 5.2.4 on 2025-07-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_post_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gamdok',
            field=models.CharField(default='봉준호', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='juyeon',
            field=models.CharField(default='김동하', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='runningtime',
            field=models.IntegerField(default=120),
        ),
    ]
