# Generated by Django 5.2.4 on 2025-07-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_post_gamdok_post_juyeon_post_runningtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('action', '액션'), ('comedy', '코미디'), ('drama', '드라마'), ('horror', '호러'), ('romance', '로맨스'), ('sci-fi', 'SF'), ('thriller', '스릴러'), ('ani', '애니메이션')], max_length=20),
        ),
    ]
