# Generated by Django 5.2 on 2025-07-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sw_idea", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devtool",
            name="kind",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="devtool",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
